name: Server Build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Remote Commands
      - uses: actions/checkout@v2

        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          password: ${{ secrets.SSH_PEM_KEY }}
          timeout: 40s  # 30초 기본

          script: whoami