name: Server Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Server Build
    runs-on: ubuntu-latest

    steps:
      - name: Server Deploy
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PEM_KEY }}
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
#          script: |
#            whoami
#            cd ./GitHub/node-express-crud-api/
#            git pull
#            npm i