name: Server Build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

  Deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH Remote Commands
      - uses: appleboy/ssh-action@v0.1.4

        env:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          PRIVATE_KEY: ${{ secrets.SSH_PEM_KEY }}
          timeout: 40s  # 30초 기본

          script: |
            whoami
            cd ./GitHub/node-express-crud-api/
            git pull
            npm i