name: Server Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Server Build
    runs-on: ubuntu-latest

    steps:
      - name: Server Deploy

        uses: appleboy/ssh-action@master

        env:
          GITHUB_TOKEN: ${{ secrets.REPOSITORY_GITHUB_TOKEN }}

        with:
          host: ${{ secrets.REMOTE_IP }}
          key: ${{ secrets.SSH_PEM_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}

          script: |
            whoami
            cd ./GitHub/node-express-crud-api/
            git pull
            npm i